# Generated by Django 3.2.5 on 2021-11-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTypes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
