# Generated by Django 3.2.5 on 2021-11-27 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digit_visit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontypes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='DataTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digit_visit_app.subscriptiontypes')),
            ],
        ),
    ]
