# Generated by Django 3.2.5 on 2021-11-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digit_visit_app', '0002_auto_20211127_1415'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataTypes',
            new_name='DataType',
        ),
        migrations.RenameModel(
            old_name='SubscriptionTypes',
            new_name='SubscriptionType',
        ),
    ]
