# Generated by Django 3.2.5 on 2021-11-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digit_visit_app', '0003_auto_20211127_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datatype',
            options={'verbose_name': 'Типы подписок', 'verbose_name_plural': 'Типы подписок'},
        ),
        migrations.AlterModelOptions(
            name='subscriptiontype',
            options={'verbose_name': 'Типы подписок', 'verbose_name_plural': 'Типы подписок'},
        ),
        migrations.RemoveField(
            model_name='datatype',
            name='sub_type',
        ),
        migrations.AddField(
            model_name='datatype',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Бесплатный'),
        ),
    ]
