# Generated by Django 3.2.5 on 2021-11-27 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('digit_visit_app', '0004_auto_20211127_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datatype',
            options={'verbose_name': 'Поле визитки', 'verbose_name_plural': 'Поля визитки'},
        ),
        migrations.AlterModelOptions(
            name='subscriptiontype',
            options={'ordering': ['price'], 'verbose_name': 'Тип подписки', 'verbose_name_plural': 'Типы подписок'},
        ),
        migrations.AlterField(
            model_name='datatype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название поля'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='duration',
            field=models.IntegerField(verbose_name='Продолжительность (в днях)'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='price',
            field=models.IntegerField(verbose_name='Стоимость'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateTimeField(editable=False)),
                ('end_date', models.DateTimeField(editable=False)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digit_visit_app.subscriptiontype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
