# Generated by Django 3.2.5 on 2021-11-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digit_visit_app', '0006_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatype',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Обязательный'),
        ),
    ]
